Repository chris2402/PollApplication, pull requests merged in 2020-10, with the labels that each got.

#65 Feat/guestrespones
  pom.xml
  src/main/java/no/hvl/dat250/h2020/group5/Main.java
  src/main/java/no/hvl/dat250/h2020/group5/controllers/GuestController.java
  src/main/java/no/hvl/dat250/h2020/group5/repositories/GuestRepository.java
  src/main/java/no/hvl/dat250/h2020/group5/repositories/UserRepository.java
  src/main/java/no/hvl/dat250/h2020/group5/responses/GuestResponse.java
  src/main/java/no/hvl/dat250/h2020/group5/service/GuestService.java
  src/test/java/no/hvl/dat250/h2020/group5/service/GuestServiceTest.java
Labels: ready to merge

#68 Test/user and vote controller
  src/main/java/no/hvl/dat250/h2020/group5/controllers/AdminController.java
  src/main/java/no/hvl/dat250/h2020/group5/controllers/PollController.java
  src/main/java/no/hvl/dat250/h2020/group5/controllers/UserController.java
  src/main/java/no/hvl/dat250/h2020/group5/controllers/VoteController.java
  src/main/java/no/hvl/dat250/h2020/group5/service/UserService.java
  src/main/lombok/no/hvl/dat250/h2020/group5/entities/User.java
  src/test/java/no/hvl/dat250/h2020/group5/controllers/AdminControllerTest.java
  src/test/java/no/hvl/dat250/h2020/group5/controllers/UserControllerTest.java
  src/test/java/no/hvl/dat250/h2020/group5/controllers/VoteControllerTest.java
  src/test/java/no/hvl/dat250/h2020/group5/service/UserServiceTest.java
Labels: ready to merge

#72 Duplicate/admin controller tests
  src/main/java/no/hvl/dat250/h2020/group5/controllers/AdminController.java
  src/main/java/no/hvl/dat250/h2020/group5/controllers/PollController.java
  src/main/java/no/hvl/dat250/h2020/group5/service/PollService.java
  src/test/java/no/hvl/dat250/h2020/group5/controllers/AdminControllerTest.java
  src/test/java/no/hvl/dat250/h2020/group5/service/PollServiceTest.java
Labels: ready to merge

#64 Test/poll controller
  src/main/java/no/hvl/dat250/h2020/group5/repositories/VoteRepository.java
  src/main/java/no/hvl/dat250/h2020/group5/service/PollService.java
  src/test/java/no/hvl/dat250/h2020/group5/controllers/GuestControllerTest.java
  src/test/java/no/hvl/dat250/h2020/group5/controllers/PollControllerTest.java
Labels: ready to merge

#83 Test/unit test guest and poll controller
  src/main/java/no/hvl/dat250/h2020/group5/controllers/PollController.java
  src/main/java/no/hvl/dat250/h2020/group5/responses/VotesResponse.java
  src/main/java/no/hvl/dat250/h2020/group5/service/PollService.java
  src/main/lombok/no/hvl/dat250/h2020/group5/entities/Guest.java
  src/main/lombok/no/hvl/dat250/h2020/group5/entities/Poll.java
  src/test/java/no/hvl/dat250/h2020/group5/controllers/GuestControllerUnitTest.java
  src/test/java/no/hvl/dat250/h2020/group5/controllers/PollControllerUnitTest.java
  src/test/java/no/hvl/dat250/h2020/group5/controllers/ResponseBodyMatchers.java
Labels: ready to merge

#80 Device-controller
  src/main/java/no/hvl/dat250/h2020/group5/controllers/VoteDeviceController.java
  src/main/java/no/hvl/dat250/h2020/group5/requests/VoteRequestFromDevice.java
  src/main/java/no/hvl/dat250/h2020/group5/service/UserService.java
  src/main/java/no/hvl/dat250/h2020/group5/service/VoteService.java
  src/main/lombok/no/hvl/dat250/h2020/group5/entities/Poll.java
  src/main/lombok/no/hvl/dat250/h2020/group5/entities/User.java
  src/main/lombok/no/hvl/dat250/h2020/group5/entities/Vote.java
  src/main/lombok/no/hvl/dat250/h2020/group5/entities/Voter.java
  src/main/lombok/no/hvl/dat250/h2020/group5/entities/VotingDevice.java
  src/test/java/no/hvl/dat250/h2020/group5/controllers/GuestControllerTest.java
  src/test/java/no/hvl/dat250/h2020/group5/controllers/VotingDeviceControllerTest.java
  src/test/java/no/hvl/dat250/h2020/group5/integrationtests/GuestControllerTest.java
  src/test/java/no/hvl/dat250/h2020/group5/repostories/PollRepositoryTest.java
  src/test/java/no/hvl/dat250/h2020/group5/repostories/VoteRepositoryTest.java
  src/test/java/no/hvl/dat250/h2020/group5/service/GuestServiceTest.java
  src/test/java/no/hvl/dat250/h2020/group5/service/UserServiceTest.java
  src/test/java/no/hvl/dat250/h2020/group5/service/VoteServiceTest.java
Labels: ready to merge

#84 Integration tests for User and Vote
  .travis.yml
  pom.xml
  src/main/java/no/hvl/dat250/h2020/group5/controllers/GuestController.java
  src/main/java/no/hvl/dat250/h2020/group5/responses/UserResponse.java
  src/main/lombok/no/hvl/dat250/h2020/group5/entities/Poll.java
  src/main/lombok/no/hvl/dat250/h2020/group5/entities/Voter.java
  src/test/java/no/hvl/dat250/h2020/group5/controllers/GuestControllerIT.java
  src/test/java/no/hvl/dat250/h2020/group5/controllers/PollControllerIT.java
  src/test/java/no/hvl/dat250/h2020/group5/controllers/PollControllerTest.java
  src/test/java/no/hvl/dat250/h2020/group5/controllers/UserControllerIT.java
  src/test/java/no/hvl/dat250/h2020/group5/controllers/UserControllerTest.java
  src/test/java/no/hvl/dat250/h2020/group5/controllers/VoteControllerIT.java
Labels: ready to merge

#92 Fix dependency between test
  pom.xml
  src/main/java/no/hvl/dat250/h2020/group5/service/PollService.java
  src/main/lombok/no/hvl/dat250/h2020/group5/entities/Poll.java
  src/main/lombok/no/hvl/dat250/h2020/group5/entities/User.java
  src/test/java/no/hvl/dat250/h2020/group5/controllers/PollControllerUnitTest.java
  src/test/java/no/hvl/dat250/h2020/group5/integrationtests/PollControllerIT.java
  src/test/java/no/hvl/dat250/h2020/group5/repostories/PollRepositoryTest.java
  src/test/java/no/hvl/dat250/h2020/group5/repostories/UserRepositoryTest.java
  src/test/java/no/hvl/dat250/h2020/group5/service/PollServiceTest.java
Labels: bug

#93 Added explanation for design
  README.md
Labels: documentation

#96 Fixed errors in tests
  src/main/lombok/no/hvl/dat250/h2020/group5/entities/Poll.java
  src/test/java/no/hvl/dat250/h2020/group5/integrationtests/PollControllerIT.java
  src/test/java/no/hvl/dat250/h2020/group5/integrationtests/VoteControllerIT.java
  src/test/java/no/hvl/dat250/h2020/group5/repostories/PollRepositoryTest.java
Labels: ready to merge

#97 Fix/update code
  src/main/java/no/hvl/dat250/h2020/group5/service/PollService.java
Labels: ready to merge

#120 More details on how to deploy to heroku
  README.md
Labels: documentation

#121 Fix/cors
  src/main/java/no/hvl/dat250/h2020/group5/controllers/AuthController.java
  src/main/java/no/hvl/dat250/h2020/group5/exceptions/UsernameAlreadyTakenException.java
  src/main/java/no/hvl/dat250/h2020/group5/security/WebSecurityConfig.java
  src/main/java/no/hvl/dat250/h2020/group5/service/UserService.java
Labels: ready to merge

#119 RabbitMQ Publisher
  README.md
  pom.xml
  src/main/java/no/hvl/dat250/h2020/group5/Main.java
  src/main/java/no/hvl/dat250/h2020/group5/Publisher.java
  src/main/java/no/hvl/dat250/h2020/group5/PublisherRunnner.java
  src/main/java/no/hvl/dat250/h2020/group5/service/PollService.java
  src/main/lombok/no/hvl/dat250/h2020/group5/entities/Poll.java
  src/test/java/no/hvl/dat250/h2020/group5/PublisherTest.java
  src/test/java/no/hvl/dat250/h2020/group5/service/PollServiceTest.java
Labels: ready to merge

#124 Fix/cookie
  src/main/java/no/hvl/dat250/h2020/group5/controllers/AuthController.java
  src/main/java/no/hvl/dat250/h2020/group5/controllers/utils/CreateCookie.java
  src/main/resources/application.properties
  src/test/resources/application.properties
Labels: ready to merge

#126 fix/duplicate votes and added new exceptions
  src/main/java/no/hvl/dat250/h2020/group5/controllers/VoteController.java
  src/main/java/no/hvl/dat250/h2020/group5/exceptions/AlreadyVotedException.java
  src/main/java/no/hvl/dat250/h2020/group5/exceptions/InvalidTimeException.java
  src/main/java/no/hvl/dat250/h2020/group5/exceptions/NotFoundException.java
  src/main/java/no/hvl/dat250/h2020/group5/service/VoteService.java
  src/test/java/no/hvl/dat250/h2020/group5/service/VoteServiceTest.java
Labels: ready to merge

#132 Admins can now make a user admin
  src/main/java/no/hvl/dat250/h2020/group5/controllers/UserController.java
  src/main/java/no/hvl/dat250/h2020/group5/requests/UpdateUserRequest.java
  src/main/java/no/hvl/dat250/h2020/group5/service/UserService.java
  src/test/java/no/hvl/dat250/h2020/group5/controllers/UserControllerTest.java
  src/test/java/no/hvl/dat250/h2020/group5/service/UserServiceTest.java
Labels: enhancement, ready to merge
